openapi: 3.1.0
info:
  title: Sample API
  description: >-
    Optional multiline or single-line description in
    [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://localhost:8000
    description: Optional server description, e.g. Main (production) server
paths:
  /customers:
    get:
      summary: Returns a list of customers.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':
          description: A JSON array of customers
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Customer'
    post:
      summary: Creates a new customer.
      description: Creates a new customer in the database.
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/NoId'
                - $ref: '#/components/schemas/Customer'
      responses:
        '201':
          description: Customer created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
components:
  schemas:
    NoId:
      type: object
      properties:
        id:
          type: integer
          description: Primary key, generated always as identity
          readOnly: true
    Customer:
      type: object
      properties:
        id:
          type: integer
          description: Primary key, generated always as identity
        datevId:
          type: integer
          description: Unique Datev ID
        name:
          type: string
          description: Customer name
          maxLength: 255
        street:
          type: string
          description: Street address
          maxLength: 255
        city:
          type: string
          description: City
          maxLength: 255
        postalCode:
          type: string
          description: Postal code
          maxLength: 255
        email:
          type: string
          description: Email address
          maxLength: 255
        phone:
          type: string
          description: Phone number
          maxLength: 255
      required:
        - id
